import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

PAIR_NUM = "0001"

base = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data_generation", "dataset", f"pair_{PAIR_NUM}")


def solve_rotation_lstsq(src_pts, dst_pts):
    """Fit rotation angle from N matched point pairs via least squares.

    For a pure rotation:  dst = R * src
        ⎡cos t  -sin t⎤ ⎡x⎤   ⎡x'⎤
        ⎣sin t   cos t⎦ ⎣y⎦ = ⎣y'⎦

    Rearranged as a linear system:
        ⎡x  -y⎤ ⎡cos t⎤   ⎡x'⎤
        ⎣y   x⎦ ⎣sin t⎦ = ⎣y'⎦

    Solve for (cos t, sin t) then recover t = atan2(sin t, cos t).
    """
    A = np.zeros((2 * len(src_pts), 2))     # coefficient matrix: 2 rows per point pair
    b = np.zeros(2 * len(src_pts))          # right-hand side: the destination coordinates
    for i, ((x, y), (xp, yp)) in enumerate(zip(src_pts, dst_pts)):
        # Each point pair contributes two rows: one for the x equation, one for y
        A[2*i]   = [ x, -y]     # x row: x*cos_t - y*sin_t = x'
        A[2*i+1] = [ y,  x]     # y row: y*cos_t + x*sin_t = y'
        b[2*i]   = xp           # destination x
        b[2*i+1] = yp           # destination y
    result, _, _, _ = np.linalg.lstsq(A, b, rcond=None)  # solve for [cos_t, sin_t]
    cos_t, sin_t = result
    # Recover the angle from the fitted (cos t, sin t) components
    angle = np.degrees(np.arctan2(sin_t, cos_t))
    return angle


def main(pair_dir, plot=False):
    pair_num = os.path.basename(pair_dir).split("_")[1]
    matched_csv   = os.path.join(pair_dir, f"centroids_matched_{pair_num}.csv")
    triangles_csv = os.path.join(pair_dir, f"triangles_{pair_num}.csv")

    # Load matched centroid positions and the triangle index table from
    # the previous two pipeline steps
    df_matched = pd.read_csv(matched_csv)
    df_tri     = pd.read_csv(triangles_csv)

    # Extract point arrays so we can index them by triangle vertex index
    pts_cand = df_matched[['x_candidate',    'y_candidate']].values
    pts_det  = df_matched[['x_detranslated', 'y_detranslated']].values

    # Solve for the rotation angle independently on every triangle. Using many
    # small subsets instead of all points at once makes the estimate robust to
    # outliers: a single bad centroid match will only corrupt the triangles that
    # include it, leaving the majority of estimates unaffected.
    angles = []
    for _, row in df_tri.iterrows():
        i, j, k = int(row['i']), int(row['j']), int(row['k'])
        src_pts = pts_cand[[i, j, k]]   # source points (where points currently are)
        dst_pts = pts_det[[i, j, k]]    # destination points (where points need to go)
        angle = solve_rotation_lstsq(src_pts, dst_pts)
        angles.append(angle)

    angles = np.array(angles)

    # Bin all per-triangle estimates and take the centre of the most populated
    # bin as the voted angle to ignore the long tails caused by degenerate triangles.
    bin_width = 0.1   # degrees
    bins      = np.arange(angles.min() - bin_width, angles.max() + bin_width, bin_width)
    counts, edges = np.histogram(angles, bins=bins)
    peak_bin    = np.argmax(counts)

    # essentially the mode of the distribution, instead of scipy.stats.mode which
    # doesn't work with bins
    voted_angle = (edges[peak_bin] + edges[peak_bin + 1]) / 2

    # Now that we have a good initial estimate from voting, run a single
    # least-squares fit over all matched pairs at once for maximum precision.
    refined_angle = solve_rotation_lstsq(pts_cand, pts_det)

    print(f"Per-triangle estimates: mean={angles.mean():.4f}°  std={angles.std():.4f}°  median={np.median(angles):.4f}°")
    print(f"Voted angle:            {voted_angle:.4f}°")
    print(f"Refined (all pairs):    {refined_angle:.4f}°")

    # Compare against the ground-truth angle stored in the needle FITS header,
    # if available (only present for synthetic data generated by this pipeline)
    from astropy.io import fits as afits
    needle_path = os.path.join(pair_dir, f"needle_{pair_num}.fits")
    if 'NANGLE' in afits.getheader(needle_path):
        true_angle = afits.getheader(needle_path)['NANGLE']
        print(f"True angle:                 {true_angle:.4f}°")
        print(f"Residual error (refined):   {abs(refined_angle - true_angle):.4f}°")
        print(f"Residual error (voted):     {abs(voted_angle - true_angle):.4f}°")

    if plot:
        fig, axes = plt.subplots(1, 2, figsize=(13, 5))

        # Histogram of per-triangle angle estimates with the voted and refined
        # angles marked. Ideally, should be a tight unimodal distribution
        axes[0].hist(angles, bins=bins, color='steelblue', edgecolor='none')
        axes[0].axvline(voted_angle,   color='orange', linewidth=1.5,               label=f'Voted  {voted_angle:.3f}°')
        axes[0].axvline(refined_angle, color='red',    linewidth=1.5, linestyle='--', label=f'Refined {refined_angle:.3f}°')
        axes[0].set_xlabel('Rotation angle (deg)')
        axes[0].set_ylabel('Triangle count')
        axes[0].set_title('Per-triangle rotation estimates')
        axes[0].legend()

        # Apply the refined rotation to the candidate centroids and measure
        # how far each rotated point lands from its matched detranslated counterpart.
        # Large residuals flag bad centroid matches or sources affected by something
        # other than pure rotation (e.g. a stretch or a localised distortion).
        theta     = np.radians(refined_angle)
        R         = np.array([[np.cos(theta), -np.sin(theta)],
                              [np.sin(theta),  np.cos(theta)]])
        rotated   = (R @ pts_cand.T).T
        residuals = np.linalg.norm(rotated - pts_det, axis=1)

        axes[1].bar(range(len(residuals)), residuals, color='mediumseagreen')
        axes[1].set_xlabel('Matched pair index')
        axes[1].set_ylabel('Residual (px)')
        axes[1].set_title(f'Per-pair residuals after rotation  (mean={residuals.mean():.3f} px)')

        plt.tight_layout()
        plt.show()

    return voted_angle, refined_angle


if __name__ == "__main__":
    main(pair_dir=base, plot=True)
